# Source: local-path-provisioner/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: local-path-config
  labels:
    app.kubernetes.io/name: local-path-provisioner
    helm.sh/chart: local-path-provisioner-0.0.22
    app.kubernetes.io/instance: local-path-provisioner
    app.kubernetes.io/version: "v0.0.22"
    app.kubernetes.io/managed-by: Helm
data:
  config.json: |-
    {
      "nodePathMap": 
        [
          {
            "node": "DEFAULT_PATH_FOR_NON_LISTED_NODES",
            "paths": [
              "/opt/local-path-provisioner"
            ]
          }
        ]
    }
  setup: |-
    
    #!/bin/sh
    set -eu
    mkdir -m 0777 -p "$VOL_DIR"
  teardown: |-
    
    #!/bin/sh
    set -eu
    rm -rf "$VOL_DIR"
  helperPod.yaml: |-
    
    apiVersion: v1
    kind: Pod
    metadata:
      name: helper-pod
    spec:
      containers:
      - name: helper-pod
        image: busybox
        imagePullPolicy: IfNotPresent
