---
# Source: local-path-provisioner/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: local-path-provisioner
  labels:
    app.kubernetes.io/name: local-path-provisioner
    helm.sh/chart: local-path-provisioner-0.0.22
    app.kubernetes.io/instance: local-path-provisioner
    app.kubernetes.io/version: "v0.0.22"
    app.kubernetes.io/managed-by: Helm
