# Source: cluster-api-aws/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: chlcd3vb3-capi-aws
  namespace: chlcd3vb3
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: chlcd3vb3-capi-aws
subjects:
- kind: ServiceAccount
  name: chlcd3vb3-capi-aws
