# Source: prometheus-process-exporter/templates/daemonset.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: run-process-exporter
subjects:
  - kind: ServiceAccount
    name: prometheus-process-exporter-process-exporter
    namespace: lma
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
