# Source: minio/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: minio
  namespace: lma
  labels:
    app.kubernetes.io/name: minio
    helm.sh/chart: minio-6.8.3
    app.kubernetes.io/instance: minio
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  access-key: "dGFjbw=="
  secret-key: "cGFzc3dvcmQ="
  key.json: ""
