# Source: eck-resource/templates/secret-elasticsearch.yaml
apiVersion: v1
kind: Secret
metadata:
  name: eck-elasticsearch-es-elastic-user
  labels:
    common.k8s.elastic.co/type: elasticsearch
    elasticsearch.k8s.elastic.co/cluster-name: eck-elasticsearch
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
  elastic: dGFjb3dvcmQ=

