# Source: eventrouter/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:     
    app: eventrouter
    heritage: Helm
    release: eventrouter
    chart: eventrouter-0.4.0
  name: eventrouter
rules:
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - get
      - list
      - watch
