# Source: eventrouter/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:     
    app: eventrouter
    heritage: Helm
    release: eventrouter
    chart: eventrouter-0.4.0
  name: eventrouter
  namespace: lma
