# Source: eck-operator/templates/webhook.yaml
apiVersion: v1
kind: Secret
metadata:
  name: elastic-webhook-server-cert
  namespace: elastic-system
  labels:
    
    control-plane: elastic-operator
    app.kubernetes.io/version: "1.8.0"
    helm.sh/chart: eck-operator-1.8.0
    app.kubernetes.io/managed-by: Helm
