# Source: eck-operator/templates/webhook.yaml
apiVersion: v1
kind: Service
metadata:
  name: elastic-webhook-server
  namespace: elastic-system
  labels:
    
    control-plane: elastic-operator
    app.kubernetes.io/version: "1.8.0"
    helm.sh/chart: eck-operator-1.8.0
    app.kubernetes.io/managed-by: Helm
spec:
  ports:
    - name: https
      port: 443
      targetPort: 9443
  selector:
    
    control-plane: elastic-operator
