# Source: kube-prometheus-stack/templates/prometheus/prometheus.yaml
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: lma-prometheus
  namespace: lma
  labels:
    app: kube-prometheus-stack-prometheus
    
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/version: "21.0.3"
    app.kubernetes.io/part-of: kube-prometheus-stack
    chart: kube-prometheus-stack-21.0.3
    release: "prometheus"
    heritage: "Helm"
spec:
  alerting:
    alertmanagers:
      - namespace: lma
        name: lma-alertmanager
        port: web
        pathPrefix: "/"
        apiVersion: v2
  image: "quay.io/prometheus/prometheus:v2.31.1"
  version: v2.31.1
  externalLabels:
    taco_cluster: cluster.local
  externalUrl: http://lma-prometheus.lma:9090
  nodeSelector:
    taco-lma: enabled
  paused: false
  replicas: 1
  shards: 1
  logLevel:  info
  logFormat:  logfmt
  listenLocal: false
  enableAdminAPI: false
  retention: "2d"
  routePrefix: "/"
  secrets:
    - etcd-client-cert
  serviceAccountName: lma-prometheus
  serviceMonitorSelector: {}
  serviceMonitorNamespaceSelector:
    matchLabels:
      name: lma

  podMonitorSelector: {}
  podMonitorNamespaceSelector:
    matchLabels:
      name: lma

  probeSelector:
    matchLabels:
      release: "prometheus"

  probeNamespaceSelector: {}
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  ruleNamespaceSelector:
    matchLabels:
      name: lma

  ruleSelector: {}
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
        storageClassName: taco-storage
  thanos:
    minTime: -3h
    objectStorageConfig:
      key: objstore.yml
      name: taco-objstore-secret
    version: v0.18.0
  portName: web
