---
# Source: cluster-autoscaler/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-autoscaler
  namespace: kube-system
  labels:
    helm.sh/chart: cluster-autoscaler-0.2.0
    app.kubernetes.io/name: cluster-autoscaler
    app.kubernetes.io/instance: cluster-autoscaler
    app.kubernetes.io/version: "1.22.2"
    app.kubernetes.io/managed-by: Helm
