# Source: cluster-autoscaler/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: cluster-autoscaler
  labels:
    helm.sh/chart: cluster-autoscaler-0.2.0
    app.kubernetes.io/name: cluster-autoscaler
    app.kubernetes.io/instance: cluster-autoscaler
    app.kubernetes.io/version: "1.22.2"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8085
      targetPort: 8085
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: cluster-autoscaler
    app.kubernetes.io/instance: cluster-autoscaler
