# Source: kubernetes-event-exporter/templates/deployment-kubernetes-event-exporter.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-event-exporter
  labels:
    helm.sh/chart: kubernetes-event-exporter-2.0.0
    app.kubernetes.io/name: event-exporter
    app.kubernetes.io/instance: kubernetes-event-exporter
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: event-exporter
        app.kubernetes.io/instance: kubernetes-event-exporter
      annotations:
        null
    spec:
      serviceAccountName: event-exporter
      containers:
      - name: event-exporter
        # The good practice would be to pin the version. This is just a reference so that we don't
        # have to update this file in each release.
        image: "ghcr.io/resmoio/kubernetes-event-exporter:v1.0"
        imagePullPolicy: IfNotPresent
        args:
          - -conf=/data/config.yaml
        volumeMounts:
        - name: shared-data
          mountPath: /tmp
        - mountPath: /data
          name: cfg
      - name: fluentbit
        image: fluent/fluent-bit:1.9.7-debug
        command: ['sh', '-c', '/fluent-bit/bin/fluent-bit -c /fluent-bit/config/fluent-bit.conf']
        env:
        - name: FLUENT_LOKI_HOST
          value: loki
        - name: FLUENT_LOKI_PORT
          value: "3100"
        volumeMounts:
        - name: shared-data
          mountPath: /tmp
        - name: cfg
          readOnly: true
          mountPath: /fluent-bit/config
      volumes:
      - name: shared-data
        emptyDir: {}
      - name: cfg
        configMap:
          name: kubernetes-event-exporter
  selector:
    matchLabels:
      app.kubernetes.io/name: event-exporter
      app.kubernetes.io/instance: kubernetes-event-exporter

