---
# Source: kubernetes-event-exporter/templates/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: event-exporter
  labels:
    helm.sh/chart: kubernetes-event-exporter-2.0.0
    app.kubernetes.io/name: event-exporter
    app.kubernetes.io/instance: kubernetes-event-exporter
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
