# Source: fluent-operator/templates/fluent-operator-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluent-operator
  labels:
    app.kubernetes.io/component: operator
    app.kubernetes.io/name: fluent-operator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: operator
      app.kubernetes.io/name: fluent-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/component: operator
        app.kubernetes.io/name: fluent-operator
    spec:
      volumes:
      - name: env
        emptyDir: {}
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
      initContainers:
      - name: setenv
        image: docker:19.03
        command:
        - /bin/sh
        - '-c'
        - set -ex;
          echo CONTAINER_ROOT_DIR=$(docker info -f '{{.DockerRootDir}}' 2> /dev/null) > /fluent-operator/fluent-bit.env
        volumeMounts:
        - name: env
          mountPath: /fluent-operator
        - name: dockersock
          readOnly: true
          mountPath: /var/run/docker.sock
      containers:
      - name: fluent-operator
        image: kubesphere/fluent-operator:v1.5.0
        resources:
          limits:
            cpu: 1000m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 20Mi
        env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
        volumeMounts:
        - name: env
          mountPath: /fluent-operator
      serviceAccountName: fluent-operator

