# Source: fluentbit-resource/templates/fluentbit/outputs.yaml
# outputs for loki---
# Loki taco-loki
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterOutput
metadata:
  name: fbcr-taco-loki-taco-loki-kube
  namespace: lma
  labels:
    fluentbit.fluent.io/enabled: "true"
    app.kubernetes.io/version: v0.0.1
spec:
  match: "kube.*"
  loki:
    autoKubernetesLabels: "on"
    host: loki
    port: 3100
    labels:
    - job=container
    - $kubernetes['pod_name']
    - $kubernetes['namespace_name']
    - $kubernetes['container_name']
