# Source: fluentbit-resource/templates/fluentbit/outputs.yaml
# Loki taco-loki
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterOutput
metadata:
  name: fbcr-taco-loki-taco-loki-syslog
  namespace: lma
  labels:
    fluentbit.fluent.io/enabled: "true"
    app.kubernetes.io/version: v0.0.1
spec:
  match: "syslog.*"
  loki:
    autoKubernetesLabels: "on"
    host: loki
    port: 3100
    labels:
    - job=syslog
    - $host
    - $ident
