# Source: fluentbit-resource/templates/fluentbit/fluentbitconfig.yaml
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterFluentBitConfig
metadata:
  name: fluent-bit-config
  namespace: lma
  labels:
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/version: v1.4.5
spec:
  service:
    parsersFile: parsers.conf
    logLevel: warning
  inputSelector:
    matchLabels:
      fluentbit.fluent.io/enabled: "true"
  filterSelector:
    matchLabels:
      fluentbit.fluent.io/enabled: "true"      
  outputSelector:
    matchLabels:
      fluentbit.fluent.io/enabled: "true"
