# Source: fluentbit-resource/templates/fluentbit/prometheus-rule.yaml
kind: PrometheusRule
apiVersion: monitoring.coreos.com/v1
metadata:
  annotations:
    prometheus-operator-validated: 'true'
  name: fbcr-taco-alert
  namespace:  taco-system
spec:
  groups:
    - name: log-based-alert
      rules:
        - alert: log-page
          annotations:
            message: >- 
              {{ $labels.container }} in {{ $labels.pod }} ({{ $labels.taco_cluster }}/{{ $labels.namespace }} ) generate a error due to log = {{ $labels.log }}
            summary: >-
              {{ $labels.container }} in {{ $labels.pod }} ({{ $labels.taco_cluster }}/{{ $labels.namespace }} ) generate a error
          expr: taco_logging_system_alert{severity="critical"} == 1
          labels:
            severity: page
        - alert: log-critical
          annotations:
            message: >- 
              {{ $labels.container }} in {{ $labels.pod }} ({{ $labels.taco_cluster }}/{{ $labels.namespace }} ) generate a error due to log = {{ $labels.log }}
            summary: >-
              {{ $labels.container }} in {{ $labels.pod }} ({{ $labels.taco_cluster }}/{{ $labels.namespace }} ) generate a error
          expr: taco_logging_system_alert{severity="critical"} == 1
          labels:
            severity: critical
        - alert: log-info
          annotations:
            message: >- 
              {{ $labels.container }} in {{ $labels.pod }} ({{ $labels.taco_cluster }}/{{ $labels.namespace }} ) generate a error due to log = {{ $labels.log }}
            summary: >-
              {{ $labels.container }} in {{ $labels.pod }} ({{ $labels.taco_cluster }}/{{ $labels.namespace }} ) generate a error
          expr: taco_logging_system_alert{severity="info"} == 1
          labels:
            severity: info
        - alert: log-warning
          annotations:
            message: >- 
              {{ $labels.container }} in {{ $labels.pod }} ({{ $labels.taco_cluster }}/{{ $labels.namespace }} ) generate a error due to log = {{ $labels.log }}
            summary: >-
              {{ $labels.container }} in {{ $labels.pod }} ({{ $labels.taco_cluster }}/{{ $labels.namespace }} ) generate a error
          expr: taco_logging_system_alert{severity="warning"} == 1
          labels:
            severity: warning
