# Source: sealed-secrets/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sealed-secrets-operator-service-proxier
  namespace: kube-system
  labels:
    app.kubernetes.io/name: sealed-secrets
    helm.sh/chart: sealed-secrets-1.16.1
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: sealed-secrets-operator
    app.kubernetes.io/version: v0.16.0
rules:
- apiGroups:
  - ""
  resourceNames:
  - 'http:sealed-secrets-operator:'
  - sealed-secrets-operator
  resources:
  - services/proxy
  verbs:
  - create
  - get
