---
# Source: sealed-secrets/templates/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sealed-secrets-operator
  namespace: kube-system
  labels:
    app.kubernetes.io/name: sealed-secrets
    helm.sh/chart: sealed-secrets-1.16.1
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: sealed-secrets-operator
    app.kubernetes.io/version: v0.16.0
