---
# Source: promtail/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: promtail
  namespace: lma
  labels:
    helm.sh/chart: promtail-3.9.1
    app.kubernetes.io/name: promtail
    app.kubernetes.io/instance: promtail
    app.kubernetes.io/version: "2.4.1"
    app.kubernetes.io/managed-by: Helm
