# Source: prepare-etcd-secret/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prepare-etcd-secret
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prepare-etcd-secret
subjects:
- kind: ServiceAccount
  name: prepare-etcd-secret
