# Source: prepare-etcd-secret/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prepare-etcd-secret
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - list
  - create
