# Source: prometheus-node-exporter/templates/psp-clusterrole.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: psp-prometheus-node-exporter
  labels:     
    app: prometheus-node-exporter
    heritage: Helm
    release: prometheus-node-exporter
    chart: prometheus-node-exporter-1.11.2
rules:
- apiGroups: ['extensions']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - prometheus-node-exporter
