# Source: prometheus-node-exporter/templates/psp-clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: psp-prometheus-node-exporter
  labels:     
    app: prometheus-node-exporter
    heritage: Helm
    release: prometheus-node-exporter
    chart: prometheus-node-exporter-1.11.2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp-prometheus-node-exporter
subjects:
  - kind: ServiceAccount
    name: prometheus-node-exporter
    namespace: lma
