# Source: prometheus-node-exporter/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-node-exporter
  namespace: lma
  labels:
    app: prometheus-node-exporter
    chart: prometheus-node-exporter-1.11.2
    release: "prometheus-node-exporter"
    heritage: "Helm"
imagePullSecrets:
  []
