---
# Source: thanos-config/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: taco-objstore-secret
  namespace: lma
stringData:
  objstore.yml: |-
    type: s3
    config:
      bucket: thanos
      endpoint: minio.lma.svc.cluster.local:9000
      access_key: taco
      secret_key: password
      insecure: true

