# Source: kube-state-metrics/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-state-metrics
  namespace: lma
  labels:
    app.kubernetes.io/name: kube-state-metrics
    helm.sh/chart: kube-state-metrics-1.1.3
    app.kubernetes.io/instance: kube-state-metrics
    app.kubernetes.io/managed-by: Helm
