{
 "title": "[TKS] Kubernetes / System / API Server",
 "description": "This is a API Server dashboard for your Kubernetes cluster(s). Made for prometheus and take advantage of the latest Grafana features. Orginated from GitHub repository: https://github.com/dotdc/grafana-dashboards-kubernetes",
 "tags": [
  "Kubernetes",
  "Prometheus",
  "tks"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "taco_cluster", "label": "Cluster", "query": { "query": "label_values(up, taco_cluster)" } },
   { "name": "resolution", "query": "1s, 15s, 30s, 1m, 3m, 5m" }
  ]
 },
 "panels": [
  { "title": "API Server ($taco_cluster)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "API Server - Health Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{taco_cluster=~\"$taco_cluster\",job=\"apiserver\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Deprecated Kubernetes Resources",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "apiserver_requested_deprecated_apis{taco_cluster=~\"$taco_cluster\"}"
    }
   ]
  },
  {
   "title": "API Server - HTTP Requests by code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (code) (rate(apiserver_request_total{taco_cluster=~\"$taco_cluster\"}[$__rate_interval]))",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "API Server - HTTP Requests by verb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (verb) (rate(apiserver_request_total{taco_cluster=~\"$taco_cluster\"}[$__rate_interval]))",
     "legendFormat": "{{ verb}}"
    }
   ]
  },
  {
   "title": "API Server - HTTP Requets Latency by instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_duration_seconds_bucket{taco_cluster=~\"$taco_cluster\",job=\"apiserver\"}[$__rate_interval])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "API Server - HTTP Requets Latency by verb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_duration_seconds_bucket{taco_cluster=~\"$taco_cluster\",job=\"apiserver\"}[$__rate_interval])) by (verb)",
     "legendFormat": "{{ verb }}"
    }
   ]
  },
  {
   "title": "API Server - Errors by Instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(apiserver_request_total{taco_cluster=~\"$taco_cluster\",code=~\"5..\", job=\"apiserver\"}[$__rate_interval]))\n / sum by(instance) (rate(apiserver_request_total{taco_cluster=~\"$taco_cluster\",job=\"apiserver\"}[$__rate_interval]))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "API Server - Errors by verb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(verb) (rate(apiserver_request_total{code=~\"5..\",job=\"apiserver\"}[$__rate_interval]))\n / sum by(verb) (rate(apiserver_request_total{job=\"apiserver\"}[$__rate_interval]))",
     "legendFormat": "{{ verb }}"
    }
   ]
  },
  {
   "title": "API Server - Stacked HTTP Requests by instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{taco_cluster=~\"$taco_cluster\"}[$__rate_interval])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "API Server - Work Queue by instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(workqueue_depth{taco_cluster=~\"$taco_cluster\",job=\"apiserver\"}[$__rate_interval])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "API Server - CPU Usage by instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{taco_cluster=~\"$taco_cluster\",job=\"apiserver\"}[$__rate_interval])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "API Server - Memory Usage by instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{taco_cluster=~\"$taco_cluster\",job=\"apiserver\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}