# Source: lma-addons/templates/service-monitor/node-exporter.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node-exporter
  labels:
    app: node-exporter
spec:
  namespaceSelector:
    matchNames:
    - lma
  selector:
    matchLabels:
      app: prometheus-node-exporter
  endpoints:
  - port: metrics
    interval: 10s
