# Source: lma-addons/templates/service-monitor/argo-workflow.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argo-workflows-server
  namespace: lma
  labels:
    release: prometheus-operator
spec:
  jobLabel: argo-workflows-server
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app.kubernetes.io/name: argo-workflows-server
  endpoints:
  - port: http
    interval: 10s
    path: "/metrics"
